apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-app-deployment
spec:
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-app-deployment
  behavior:
    scaleDown:
      stabilizationWindowSeconds:
        60
        # policies:
        # - type: Pods
        #value: 4
        #periodSeconds: 60
